# MongoDB connection details
MONGO_HOST = ""
MONGO_PORT = ""
MONGO_USERNAME = ""
MONGO_PASSWORD = ""
MONGO_DATABASE_NAME = ""
FACILITY_METADATA_MONGO_COLLECTION_NAME = ""
CLIENT_INFO_MONGO_COLLECTION_NAME = ""


# PostgreSQL connection details
POSTGRES_HOST = ""
POSTGRES_PORT = ""
POSTGRES_USERNAME = ""
POSTGRES_PASSWORD = ""
POSTGRES_DB_NAME = ""
